app:
  # 是否尝试使用自定义ip
  try_use_custom_ip: false
  # 失败次数达到总执行次数的报警终止阈值
  fail_threshold_percent: 0.25
  # wjx的地址
  url: https://www.wjx.cn/vm/tGWa7U4.aspx
  # 此次任务执行多少问卷
  target_num: 20
  # 多少线程同时执行(就1吧别动了，不知道多线程情况下同一个ip去做提交会不会有啥问题，选择串行执行)
  thread_num: 1
  # 留的后门，用于提醒目前使用过的数据是否达到这个阈值
  repeat_threshold_percent: 0.6